"""Persistence boundary used by coordinator and operator-facing APIs."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from ..study_identity import StudyIdentity


@runtime_checkable
class StudyStore(Protocol):
    """Actual local-study operations; terminal SQLite trials stay authoritative."""

    def open_study(self, identity: StudyIdentity, resume: str = "auto") -> str: ...
    def completed_param_keys(self, study_id: str) -> set[str]: ...
    def results(self, study_id: str) -> list[dict[str, Any]]: ...
    def study_state(self, study_id: str) -> dict[str, Any]: ...
    def update_study_state(self, study_id: str, state: dict[str, Any]) -> None: ...
    def commit_trial(self, study_id: str, params: dict[str, Any], result: dict[str, Any]) -> bool: ...
    def clear(self) -> None: ...
    def close(self) -> None: ...
